// Generic SD formats. Brand-neutral — shared across projects.
//   tokenkit/tailwind-theme — emits a Tailwind v4 `@theme { --color-*: … }` block
//   tokenkit/grid-ts        — emits a typed `as const` object for canvas/JS consumers
//
// The "AUTO-GENERATED" banner is brand-neutral by default so a consuming
// project's generated files carry no foreign branding. Override it per
// project via the Style Dictionary file `options.banner` (e.g. to name
// your own tool + regen command):
//   files: [{ format: 'tokenkit/tailwind-theme', options: {
//     banner: '/* AUTO-GENERATED by acme-tokens — run `npm run tokens`. */' } }]
const v = (t) => t.value ?? t.$value;
const DEFAULT_BANNER = '/* AUTO-GENERATED — DO NOT EDIT. */';
const blockBanner = (options) => options?.banner ?? DEFAULT_BANNER;

export const formats = [
  {
    name: 'tokenkit/tailwind-theme',
    format: ({ dictionary, options }) =>
      `${blockBanner(options)}\n@theme {\n` +
      dictionary.allTokens.map((t) => `  --color-${t.name}: ${v(t)};`).join('\n') +
      `\n}\n`,
  },
  {
    name: 'tokenkit/grid-ts',
    format: ({ dictionary, options }) =>
      `${blockBanner(options).replace('/* ', '// ').replace(' */', '')}\n` +
      `export const TOKENS = {\n` +
      dictionary.allTokens.map((t) => `  ${JSON.stringify(t.name)}: ${JSON.stringify(v(t))},`).join('\n') +
      `\n} as const;\n\nexport type TokenName = keyof typeof TOKENS;\n`,
  },
];
