// Generic SD formats. Brand-neutral — shared across projects.
//   tokenkit/tailwind-theme — emits a Tailwind v4 `@theme { --color-*: … }` block
//   tokenkit/grid-ts        — emits a typed `as const` object for canvas/JS consumers
const v = (t) => t.value ?? t.$value;
const BANNER = '/* AUTO-GENERATED by @papercusp/design-tokens — DO NOT EDIT. Run `npm run tokens`. */';

export const formats = [
  {
    name: 'tokenkit/tailwind-theme',
    format: ({ dictionary }) =>
      `${BANNER}\n@theme {\n` +
      dictionary.allTokens.map((t) => `  --color-${t.name}: ${v(t)};`).join('\n') +
      `\n}\n`,
  },
  {
    name: 'tokenkit/grid-ts',
    format: ({ dictionary }) =>
      `${BANNER.replace('/* ', '// ').replace(' */', '')}\n` +
      `export const TOKENS = {\n` +
      dictionary.allTokens.map((t) => `  ${JSON.stringify(t.name)}: ${JSON.stringify(v(t))},`).join('\n') +
      `\n} as const;\n\nexport type TokenName = keyof typeof TOKENS;\n`,
  },
];
